# This playbook is for Amazon Linux
- hosts: server
  tasks:
    - name: yum update
      yum: state=latest name=*
    - name: install gcc-c++
      yum: state=latest name=gcc-c++
    - name: install docker
      yum: state=latest name=docker
    - name: start docker
      service:
        name=docker state=started enabled=yes